# Generated by Django 4.2 on 2025-05-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_upload_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
