# Generated by Django 4.2 on 2025-05-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_upload_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='original_filename',
        ),
    ]
