# Generated by Django 4.2 on 2025-05-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_upload_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
